Web\Bundle\UserBundle\Entity\RoomInvite:
    type: entity
    table: invites
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        token:
            type: string
            length: 40
            nullable: false
    oneToOne:
       user:
            targetEntity: User
            inversedBy: invite
            joinColumn:
                name: user_id
                referencedColumnName: id