<?php

namespace Web\Bundle\UserBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    /**
     * @param \DateTime $delay
     * @return \Doctrine\ORM\QueryBuilder
     */
    public function getActiveQueryBuilder(\DateTime $delay = null)
    {
        if ($delay == null) {
            $delay = new \DateTime();
            $delay->modify('-1 min');
        }

        $qb = $this->createQueryBuilder('u')
            ->where('u.lastActivity > :delay')
            ->setParameter('delay', $delay)
        ;

        return $qb;
    }

    /**
     * @param \DateTime $delay
     * @return \Web\Bundle\UserBundle\Entity\User[]
     */
    public function getActive(\DateTime $delay = null)
    {
        return $this->getActiveQueryBuilder($delay)
            ->getQuery()
            ->getResult();
    }
}
