parameters:
#    web_user.example.class: Web\Bundle\UserBundle\Example

services:
    activity_listener:
        class: Web\Bundle\UserBundle\EventListener\ActivityListener
        arguments: [@security.context, @doctrine.orm.entity_manager, %web_user.interval%, @session]
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onController }

    web_user.form.type.invite:
        class: Web\Bundle\UserBundle\Form\Type\UserType
        arguments: [@doctrine.orm.entity_manager]
        tags:
            - { name: form.type, alias: user }