parameters:
#    web_user.example.class: Web\Bundle\UserBundle\Example

services:
#    web_user.example:
#        class: %web_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
