parameters:
    web_socket.server.command.class: Web\SocketBundle\Command\ServerCommand

services:
    web_socket.server.command:
        class: %web_socket.server.command.class%
        arguments: [@doctrine.orm.entity_manager]
        tags:
            -  { name: console.command }
